[package]
name = "cookie-tampering"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-session = { version = "0.7", features = ["cookie-session"] }
base64 = "0.21"
serde = { version = "1.0", features = ["derive"] }
